deployment:
  imageRepo: tonyduck/frontend-deploy
  imageVersion: v1
  replicas: 1
service:
  servicePort: 80
  targetPort: 80
  containerPort: 80

   # default value {{ .Values.service.servicePort }}
   #{{ .Values.service.targetPort }}

# {{ .Values.deployment.imageRepo }}