deployment:
  imageRepo: tonyduck/frontend
  imageVersion: v3
  replicas: 3
service:
  servicePort: 80
  targetPort: 80
  containerPort: 80

   # default value {{ .Values.service.servicePort }}
   #{{ .Values.service.targetPort }}

# {{ .Values.deployment.imageRepo }}